export { MoodleClient } from './client.js';
export { MoodleHttpClient } from './http.js';

export {
  MoodleApiError,
  MoodleAuthenticationError,
  MoodleAuthorizationError,
  MoodleClientError,
  MoodleConflictError,
  MoodleInvalidParameterError,
  MoodleNetworkError,
  MoodleResourceNotFoundError,
  MoodleResponseError,
  isRawMoodleException,
  normalizeMoodleError,
} from './errors.js';

export {
  appendDefined,
  serializeAddQuestionToQuizParams,
  serializeCreateAssignmentParams,
  serializeCreateCourseParams,
  serializeCreateQuizParams,
  serializeCreateQuizQuestionParams,
  serializeCreateResourceParams,
  serializeCreateSectionParams,
  serializeQuestionOptions,
  serializeUpdateAssignmentParams,
  serializeUpdateQuizParams,
  serializeUpdateQuizQuestionParams,
} from './serializers.js';

export {
  parseAddedQuestionSlot,
  parseAssignmentDetails,
  parseCategories,
  parseCourseFormats,
  parseCourseStructure,
  parseCreatedAssignment,
  parseCreatedCourse,
  parseCreatedQuestion,
  parseCreatedResource,
  parseCreatedQuiz,
  parseCreatedSection,
  parseQuizDetails,
  parseQuizQuestionSlots,
  parseUpdatedAssignment,
  parseUpdatedQuestion,
  parseUpdatedQuiz,
} from './response-validators.js';

export type {
  CompetencyFrameworkPreflightParams,
  MoodleCompetencyFrameworkPreflight,
  AddQuestionToQuizParams,
  CreateAssignmentParams,
  CreateCourseParams,
  CreateEssayQuestionParams,
  CreateMultichoiceQuestionParams,
  CreateQuizParams,
  CreateQuizQuestionParams,
  CreateResourceParams,
  CreateQuizQuestionParamsBase,
  CreateSectionParams,
  CreateShortAnswerQuestionParams,
  CreateTrueFalseQuestionParams,
  EssayQuestionOptions,
  MoodleAddedQuestionSlot,
  MoodleAssignmentDetails,
  MoodleCategory,
  MoodleCourseFormat,
  MoodleClientConfig,
  MoodleCourseStructure,
  MoodleCreatedAssignment,
  MoodleCreatedCourse,
  MoodleCreatedQuestion,
  MoodleCreatedResource,
  MoodleCreatedQuiz,
  MoodleCreatedSection,
  MoodleQuizDetails,
  MoodleQuizQuestionAnswer,
  MoodleQuizQuestionSlot,
  MoodleStructureActivity,
  MoodleStructureSection,
  MoodleUpdatedAssignment,
  MoodleUpdatedQuestion,
  MoodleUpdatedQuiz,
  MultichoiceOptionChoice,
  MultichoiceQuestionOptions,
  QuestionOptions,
  RawMoodleException,
  ShortAnswerQuestionOptions,
  SupportedQuestionType,
  TrueFalseQuestionOptions,
  UpdateAssignmentParams,
  UpdateEssayQuestionParams,
  UpdateMultichoiceQuestionParams,
  UpdateQuizParams,
  UpdateQuizQuestionMetadataOnly,
  UpdateQuizQuestionParams,
  UpdateQuizQuestionParamsBase,
  UpdateShortAnswerQuestionParams,
  UpdateTrueFalseQuestionParams,
} from './types.js';
