import { randomUUID } from "node:crypto";
import type { ModelClient, PlanRepository } from "@moodle-agent-poc/agent-runtime";
import {
  validatePlanningContract,
  type AnyPlanEnvelope,
  type CoursePlanEnvelope,
  type NormalizedSyllabus,
} from "@moodle-agent-poc/contracts";
import {
  buildProvenanceAllowlist,
  validatePlanningDomainInvariants,
} from "../domain/planning-domain-validator.js";
import { PlanningError } from "../errors/planning-errors.js";
import type { SectionStructureDraft } from "../types.js";
import { interpretTeacherInstruction } from "../instructions/teacher-instruction-interpreter.js";
import { CourseStructurePlanner } from "./course-structure-planner.js";
import { ActivityPlanner, assembleCoursePlanContent, splitActivityChunks } from "./activity-planner.js";
import { getPlanningProgress, setPlanningProgress } from "../planning-progress.js";
import { buildTeacherActivityRefMap, validateCourseActivityConstraints, validateSectionActivityProvenance, resolveActivityRuleScopes, type ActivityRuleScopeMap, type TeacherActivityRefMap } from "../validators/teacher-constraint-validator.js";
import { buildSectionGrounding, buildSectionProvenanceAllowlists } from "../grounding/section-grounding.js";
import { validateCourseStructureCoverage } from "../validators/course-structure-coverage-validator.js";

export interface CoursePlannerOptions {
  modelClient: ModelClient;
  planRepository?: PlanRepository | undefined;
}

export interface GenerateCoursePlanParams {
  syllabus: NormalizedSyllabus;
  runId?: string;
  planId?: string;
  model?: string;
  timeoutMs?: number;
  teacherInstruction?: string;
}

export class CoursePlanner {
  private readonly modelClient: ModelClient;
  private readonly planRepo: PlanRepository | undefined;

  constructor(options: CoursePlannerOptions) {
    this.modelClient = options.modelClient;
    this.planRepo = options.planRepository;
  }

  /** Stable orchestration entry point; generateCoursePlan remains compatible with existing callers. */
  async plan(params: GenerateCoursePlanParams): Promise<CoursePlanEnvelope> {
    return this.generateCoursePlan(params);
  }

  async generateCoursePlan(
    params: GenerateCoursePlanParams
  ): Promise<CoursePlanEnvelope> {
    const { syllabus, runId, planId } = params;

    setPlanningProgress(runId, { stage: "interpreting_teacher_instruction" });
    const constraints = interpretTeacherInstruction(params.teacherInstruction);

    // Stage 1: structure only. Activity bodies are always generated by Stage 2.
    setPlanningProgress(runId, { stage: "planning_structure" });
    const structurePlanner = new CourseStructurePlanner(this.modelClient);
    let structure;
    try {
      structure = await structurePlanner.plan(syllabus, constraints, params.model, params.timeoutMs);
    } catch (error) {
      if (this.isDeterministicTokenBudgetFailure(error)) {
        throw new PlanningError("TOKEN_BUDGET_EXCEEDED", `Deterministic token budget failure while planning course structure. ${error instanceof Error ? error.message : String(error)}`, { cause: error });
      }
      if (["MODEL_TIMEOUT", "MODEL_RATE_LIMITED", "MODEL_PROVIDER_UNAVAILABLE", "MODEL_NOT_FOUND"].includes((error as any)?.code)) throw error;
      if (error instanceof PlanningError) throw error;
      throw new PlanningError("MODEL_RESPONSE_INVALID", error instanceof Error ? error.message : String(error), null, error instanceof Error ? { cause: error } : {});
    }
    const sections = structure.content.sections;
    const ruleScopes = resolveActivityRuleScopes(constraints.activityRules, sections, syllabus);
    validateCourseStructureCoverage(syllabus, sections);
    const normalizedSections = this.addInstructionIntents(sections, constraints.activityRules, syllabus, ruleScopes);
    const teacherActivityRefs = buildTeacherActivityRefMap(normalizedSections);
    const chunks = splitActivityChunks(normalizedSections);
    const activityPlanner = new ActivityPlanner(this.modelClient);
    const chunkResults = [];
    setPlanningProgress(runId, { stage: "generating_activities", completedChunks: 0, totalChunks: chunks.length, completedSections: 0, totalSections: normalizedSections.length, currentSectionRefs: chunks[0]?.map((s) => s.ref) ?? [] });
    for (let index = 0; index < chunks.length; index++) {
      const chunk = chunks[index]!;
      let result;
      try {
        result = await activityPlanner.generateChunk(syllabus, chunk, constraints, params.model, params.timeoutMs, ruleScopes);
      } catch (error) {
        if (this.isDeterministicTokenBudgetFailure(error) && chunk.length > 1) {
          chunks.splice(index, 1, ...chunk.map((section) => [section]));
          const completedSections = chunks.slice(0, index).reduce((count, currentChunk) => count + currentChunk.length, 0);
          setPlanningProgress(runId, { stage: "generating_activities", completedChunks: index, totalChunks: chunks.length, completedSections, totalSections: normalizedSections.length, currentSectionRefs: chunks[index]?.map((section) => section.ref) ?? [] });
          index--;
          continue;
        }
        if ((error as any)?.code === "TEACHER_CONSTRAINT_VIOLATION") {
          throw new PlanningError("TEACHER_CONSTRAINT_VIOLATION", error instanceof Error ? error.message : String(error), (error as any).details);
        }
        if (this.isDeterministicTokenBudgetFailure(error)) throw new PlanningError("TOKEN_BUDGET_EXCEEDED", error instanceof Error ? error.message : String(error), { cause: error });
        if (["MODEL_TIMEOUT", "MODEL_RATE_LIMITED", "MODEL_PROVIDER_UNAVAILABLE", "MODEL_NOT_FOUND"].includes((error as any)?.code)) throw error;
        throw new PlanningError("MODEL_RESPONSE_INVALID", error instanceof Error ? error.message : String(error), null, error instanceof Error ? { cause: error } : {});
      }
      chunkResults.push(result);
      const completedSections = chunks.slice(0, index + 1).reduce((count, currentChunk) => count + currentChunk.length, 0);
      setPlanningProgress(runId, { stage: "generating_activities", completedChunks: index + 1, totalChunks: chunks.length, completedSections, totalSections: normalizedSections.length, currentSectionRefs: chunks[index + 1]?.map((s) => s.ref) ?? [] });
    }
    setPlanningProgress(runId, { stage: "assembling_plan" });
    const content = assembleCoursePlanContent({ course: structure.content.course, sections: normalizedSections as any }, chunkResults);
    return this.persistAndValidate({ syllabus, runId, planId, title: structure.title, summary: structure.summary, warnings: [...structure.warnings, ...constraints.warnings], assumptions: structure.assumptions, content, constraints, chunkCount: chunks.length, ruleScopes, teacherActivityRefs }, params);

  }

  private addInstructionIntents(sections: SectionStructureDraft[], rules: import("../instructions/planning-constraints.js").ActivityRule[], syllabus: NormalizedSyllabus, ruleScopes: ActivityRuleScopeMap): SectionStructureDraft[] {
    return sections.map((section, index) => {
      const intents = section.activityIntents.filter((intent) => intent.origin === "syllabus");
      for (const rule of rules) {
        const applies = rule.scope === "specific_sections" ? (ruleScopes.get(rule)?.has(section.position) ?? false) : rule.scope === "every_n_sections" ? Boolean(rule.interval && section.position % rule.interval === 0) : true;
        if (!applies) continue;
        const count = rule.activityCount ?? 1;
        const existingCount = intents.filter((intent) => intent.type === rule.activityType && intent.origin === "teacher_instruction").length;
        for (let i = existingCount; i < count; i++) {
          const label = rule.activityType === "quiz" ? "Quiz" : "Assignment";
          intents.push({
            type: rule.activityType,
            title: `${label}${count > 1 ? ` ${i + 1}` : ""}: ${section.title}`,
            source_refs: [...section.source_refs],
            origin: "teacher_instruction",
          });
        }
      }
      const sectionKey = section.ref.replace(/^section-/, "") || String(index + 1).padStart(2, "0");
      const typeCounts = new Map<string, number>();
      const titleCounts = new Map<string, number>();
      const usedRefs = new Set<string>();
      return {
        ...section,
        activityIntents: intents.map((intent) => {
          const count = (typeCounts.get(intent.type) ?? 0) + 1;
          typeCounts.set(intent.type, count);
          const titleKey = `${intent.type}:${intent.title.trim()}`;
          const titleCount = (titleCounts.get(titleKey) ?? 0) + 1;
          titleCounts.set(titleKey, titleCount);
          const title = intent.origin === "teacher_instruction" && titleCount > 1
            ? `${intent.title.trim()} ${titleCount}`
            : intent.title;
          const generatedRef = `${intent.type}-${sectionKey}-${String(count).padStart(2, "0")}`;
          const ref = !intent.ref || usedRefs.has(intent.ref) ? generatedRef : intent.ref;
          usedRefs.add(ref);
          return {
            ...intent,
            ref,
            title,
          };
        }),
      };
    });
  }

  private async persistAndValidate(input: { syllabus: NormalizedSyllabus; runId: string | undefined; planId: string | undefined; title: string; summary: string; warnings: string[]; assumptions: string[]; content: CoursePlanEnvelope["content"]; constraints: import("../instructions/planning-constraints.js").CoursePlanningConstraints; chunkCount?: number; ruleScopes: ActivityRuleScopeMap; teacherActivityRefs: TeacherActivityRefMap }, params: GenerateCoursePlanParams): Promise<CoursePlanEnvelope> {
    setPlanningProgress(params.runId, { stage: "validating_teacher_constraints" });
    const sectionAllowlists = buildSectionProvenanceAllowlists(input.syllabus, input.content.sections);
    const constraintViolations = [
      ...validateCourseActivityConstraints(input.content, input.constraints, input.syllabus, input.ruleScopes, input.teacherActivityRefs),
      ...input.content.sections.flatMap((section) => validateSectionActivityProvenance(section, sectionAllowlists.get(section.ref))),
    ];
    if (constraintViolations.length > 0) {
      throw new PlanningError("TEACHER_CONSTRAINT_VIOLATION", `Teacher constraints failed during final plan assembly: ${JSON.stringify(constraintViolations)}`, constraintViolations);
    }
    const effectivePlanId = input.planId || randomUUID();
    const envelope: CoursePlanEnvelope = { schema_version: "0.1", plan_id: effectivePlanId, revision: 1, plan_type: "course", operation: "create", title: input.title, summary: input.summary, warnings: input.warnings, assumptions: input.assumptions, content: input.content };
    setPlanningProgress(params.runId, { stage: "validating_contract" });
    const validation = validatePlanningContract(envelope as unknown as AnyPlanEnvelope);
    if (!validation.valid) {
      const errorMsg = validation.errors.map((err) => `${err.instancePath || "/"}: ${err.message}`).join("; ");
      throw new PlanningError("PLAN_SCHEMA_INVALID", `Generated CoursePlan failed schema contract validation: ${errorMsg}`, validation.errors);
    }
    const allowlist = buildProvenanceAllowlist(input.syllabus);
    validatePlanningDomainInvariants(envelope, allowlist, sectionAllowlists);
    if (this.planRepo && input.runId) await this.planRepo.savePlanRevision({ id: randomUUID(), planId: effectivePlanId, runId: input.runId, planType: "course", operation: "create", revision: 1, title: envelope.title, summary: envelope.summary, content: envelope.content as unknown as Record<string, unknown>, rawEnvelope: envelope as unknown as AnyPlanEnvelope, validationStatus: "valid" });
    setPlanningProgress(params.runId, {
      stage: "ready_for_preview",
      completedSections: envelope.content.sections.length,
      totalSections: envelope.content.sections.length,
      ...(input.chunkCount !== undefined ? { completedChunks: input.chunkCount, totalChunks: input.chunkCount } : {}),
    });
    return envelope;
  }

  getPlanningProgress(runId: string) { return getPlanningProgress(runId); }

  private isDeterministicTokenBudgetFailure(err: unknown): boolean {
    if (!err) return false;
    const msg = (err instanceof Error ? err.message : String(err)).toLowerCase();
    const code = (err as any)?.code;

    if (code === "MODEL_REQUEST_TOO_LARGE" || code === "TOKEN_BUDGET_EXCEEDED") {
      return true;
    }

    if (
      msg.includes("413") ||
      msg.includes("request too large") ||
      msg.includes("context_length_exceeded") ||
      msg.includes("maximum context length")
    ) {
      return true;
    }

    // Check for Groq / provider token patterns: "limit X, requested Y"
    const match =
      msg.match(/limit\s*[:=]?\s*(\d+).*?requested\s*[:=]?\s*(\d+)/i) ||
      msg.match(/requested\s*[:=]?\s*(\d+).*?limit\s*[:=]?\s*(\d+)/i);
    if (match) {
      return true;
    }

    return false;
  }

}
